#!/bin/sh

set -e

# inherit first, overide later
. `dirname $0`/config.base

# Main network interface
main_int="vio0"

# Main IPv4 address
main_ipv4="127.0.0.1"

# sshd(8) non-standard listening port
sshd_port="12322"
